wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1676369443.272727
    t:
      1:
      - 1
      - 50
      - 55
      2:
      - 1
      - 50
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.7.13
      5: 0.13.9
      8:
      - 5
batch_size:
  desc: null
  value: 64
disable_progressbar:
  desc: null
  value: false
discount_factor:
  desc: null
  value: 0.99
experiment:
  desc: null
  value:
    checkpoint_interval: 800
    directory: ''
    experiment_name: ''
    store_separately: false
    wandb: true
    wandb_kwargs: {}
    write_interval: 80
exploration:
  desc: null
  value:
    final_epsilon: 0.05
    initial_epsilon: 1.0
    timesteps: 1000
gradient_steps:
  desc: null
  value: 1
headless:
  desc: null
  value: true
learning_rate:
  desc: null
  value: 0.001
learning_rate_scheduler:
  desc: null
  value: null
learning_rate_scheduler_kwargs:
  desc: null
  value: {}
learning_starts:
  desc: null
  value: 0
polyak:
  desc: null
  value: 0.005
q_network:
  desc: null
  value:
    '0': Linear(in_features=18, out_features=256, bias=True)
    '1': Tanh()
    '2': Linear(in_features=256, out_features=256, bias=True)
    '3': Tanh()
    '4': Linear(in_features=256, out_features=128, bias=True)
    '5': Tanh()
random_timesteps:
  desc: null
  value: 0
rewards_shaper:
  desc: null
  value: __main__.<lambda>
state_preprocessor:
  desc: null
  value: null
state_preprocessor_kwargs:
  desc: null
  value: {}
target_q_network:
  desc: null
  value:
    '0': Linear(in_features=18, out_features=256, bias=True)
    '1': Tanh()
    '2': Linear(in_features=256, out_features=256, bias=True)
    '3': Tanh()
    '4': Linear(in_features=256, out_features=128, bias=True)
    '5': Tanh()
target_update_interval:
  desc: null
  value: 10
timesteps:
  desc: null
  value: 16000
update_interval:
  desc: null
  value: 1
