wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1676378123.650124
    t:
      1:
      - 1
      - 50
      - 55
      2:
      - 1
      - 50
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.7.13
      5: 0.13.9
      8:
      - 5
clip_predicted_values:
  desc: null
  value: true
disable_progressbar:
  desc: null
  value: false
discount_factor:
  desc: null
  value: 0.99
entropy_loss_scale:
  desc: null
  value: 0.0
experiment:
  desc: null
  value:
    checkpoint_interval: 800
    directory: ''
    experiment_name: ''
    store_separately: false
    wandb: true
    wandb_kwargs: {}
    write_interval: 80
grad_norm_clip:
  desc: null
  value: 1.0
headless:
  desc: null
  value: true
kl_threshold:
  desc: null
  value: 0
lambda:
  desc: null
  value: 0.95
learning_epochs:
  desc: null
  value: 8
learning_rate:
  desc: null
  value: 0.0001
learning_rate_scheduler:
  desc: null
  value: skrl.resources.schedulers.torch.kl_adaptive.KLAdaptiveRL
learning_rate_scheduler_kwargs:
  desc: null
  value:
    kl_threshold: 0.016
learning_starts:
  desc: null
  value: 0
mini_batches:
  desc: null
  value: 4
policy:
  desc: null
  value:
    '0': Linear(in_features=18, out_features=256, bias=True)
    '1': Tanh()
    '2': Linear(in_features=256, out_features=256, bias=True)
    '3': Tanh()
    '4': Linear(in_features=256, out_features=128, bias=True)
    '5': Tanh()
random_timesteps:
  desc: null
  value: 0
ratio_clip:
  desc: null
  value: 0.2
rewards_shaper:
  desc: null
  value: __main__.<lambda>
rollouts:
  desc: null
  value: 16
state_preprocessor:
  desc: null
  value: skrl.resources.preprocessors.torch.running_standard_scaler.RunningStandardScaler
state_preprocessor_kwargs:
  desc: null
  value:
    device: cuda:0
    size: "Box([-inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf\n\
      \ -inf -inf -inf -inf], [inf inf inf inf inf inf inf inf inf inf inf inf inf\
      \ inf inf inf inf inf], (18,), float32)"
timesteps:
  desc: null
  value: 16000
value:
  desc: null
  value:
    '0': Linear(in_features=18, out_features=256, bias=True)
    '1': Tanh()
    '2': Linear(in_features=256, out_features=256, bias=True)
    '3': Tanh()
    '4': Linear(in_features=256, out_features=128, bias=True)
    '5': Tanh()
value_clip:
  desc: null
  value: 0.2
value_loss_scale:
  desc: null
  value: 1.0
value_preprocessor:
  desc: null
  value: skrl.resources.preprocessors.torch.running_standard_scaler.RunningStandardScaler
value_preprocessor_kwargs:
  desc: null
  value:
    device: cuda:0
    size: 1
